### ISSUE TITLE
Move Resume upload above create hacker fields

### ISSUE THREAD

**Issue by aileenpongnon** [KnightHacks/hackathon-2021-frontend#54]

**Comment by TorrentofShame** [comment]
You don't necessarily need to change the location of the "upload resume" button, just having a small resume upload progress bar appear when you submit a resume and prevent the user from submitting the form until the resume is done uploading would suffice.

The idea is that even though the total time spent submitting/filling out the resume might be the same, it will feel shorter since they are in separate steps.

If you want an example of what I'm talking about, I can probably give that to you.
